In [14]:
import numpy as np

In [15]:
print(np.__version__)

1.15.3


In [16]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [25]:
Z = np.zeros((10,10))
print(Z.size)
print(Z.itemsize)
print("%d bytes" % (Z.size * Z.itemsize))
# print(Z)

100
8
800 bytes


In [33]:
Z = np.arange(10, 60)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59]


In [29]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [37]:
Z = np.arange(11, 20).reshape(3,3)
print(Z)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [38]:
# find index of non-zero elements
Z = np.nonzero([1,2,0,0,4,0])
print(Z)

(array([0, 1, 4]),)


In [39]:
# 3 * 3 * 3 cube
Z = np.random.random((3,3,3))
print(Z)

[[[0.5613411  0.70364567 0.69646077]
  [0.55349181 0.36073962 0.42407304]
  [0.03557873 0.78106683 0.38925712]]

 [[0.01939523 0.98954461 0.10429208]
  [0.93266211 0.3930714  0.98307604]
  [0.27858378 0.34264326 0.23949413]]

 [[0.00406519 0.94208236 0.8958865 ]
  [0.51338416 0.68963128 0.64881672]
  [0.62846941 0.12174536 0.01650108]]]


In [45]:
Z = np.random.random((10,10))
print(Z.min(), Z.max())
print(Z.mean())

0.022585689314327917 0.9942915482651247
0.5449976128759547


In [46]:
# Create a 2d array with 1 on the border and 0 inside
Z = np.ones((10,10))
Z[1:-1, 1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [48]:
# 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
Z = np.ones((3,3))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [49]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [54]:
Z = np.diag(1+np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [55]:
Z = np.diag(1+np.arange(4), k=1)
print(Z)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [57]:
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
Z = np.zeros((8,8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [59]:
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?¶
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [61]:
# ???
# 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [63]:
# ???
# 22. Normalize a 5x5 random matrix (★☆☆)
Z = np.random.random((5,5))
Z = (Z - np.mean(Z)) / (np.std(Z))
print(Z)

[[-0.03547183 -0.26042566  1.61912465 -0.70866286  0.29251833]
 [-1.07906877 -0.53453043 -1.50093059  1.28216997  1.06867628]
 [-1.38105696  0.59996049 -1.47801801 -1.06504086  1.69518305]
 [ 0.11996419  1.33942907 -0.35757269 -0.14051125  0.08751463]
 [-0.50325021  1.51706851  0.67387101 -1.33886991  0.08792983]]


In [65]:
# ???
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [67]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
# Alternative solution in Python 3.5 or above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [81]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
Z = np.arange(11)
Z[(Z > 3) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [82]:
# ???
# 26. What is the output of the following script? (★☆☆)
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [93]:
# Z**Z
# 2 << Z >> 2
# Z <- Z 
# 1j*Z
# Z/1/1 
# Z<Z>Z # illegal

array([                 0,                  1,                  2,
                        4, 576460752303423488, 288230376151711744,
       144115188075855872,  72057594037927936,  36028797018963968,
                      256,                512])

In [99]:
# print(np.array(0)/ np.array(0))
# print(np.array(0)// np.array(0))
# print(np.array([np.nan]).astype(int).astype(float))

In [123]:
# 29. How to round away from zero a float array ?(★☆☆)
Z = np.random.uniform(-10, +10, 6)
print(Z)
print(np.ceil(np.abs(Z)))
print(np.copysign(np.ceil(np.abs(Z)), Z))


[-5.84421071  7.6335547   5.69200138  6.34658185  6.52387359  4.66705681]
[6. 8. 6. 7. 7. 5.]
[-6.  8.  6.  7.  7.  5.]


In [128]:
# 30. How to find common values between two arrays? (★☆☆)
Z1 = np.random.randint(0, 10, 6)
Z2 = np.random.randint(0, 10, 4)
print(Z1)
print(Z2)
print(np.intersect1d(Z1, Z2))


[6 6 2 8 4 2]
[7 1 6 0]
[6]


In [133]:
# 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# An equivalent way, with a context manager:

# with np.errstate(divide='ignore'):
#     Z = np.ones(1) / 0

In [134]:
np.sqrt(-1) == np.emath.sqrt(-1) # False

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [136]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2018-11-10
2018-11-11
2018-11-12


In [137]:
# 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [147]:
# 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [154]:
# 36. Extract the integer part of a random array using 5 different methods (★★☆)
Z = np.random.uniform(0, 10, 6)
print(Z)
print(Z - Z%1)
print(np.floor(Z))
print(np.ceil(Z) - 1)
print(np.trunc(Z))
print(Z.astype(int))

[4.73654853 9.20938563 8.64766538 2.90536276 1.89527838 6.88214825]
[4. 9. 8. 2. 1. 6.]
[4. 9. 8. 2. 1. 6.]
[4. 9. 8. 2. 1. 6.]
[4. 9. 8. 2. 1. 6.]
[4 9 8 2 1 6]


In [156]:
# 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
Z = np.zeros((5,5))
print(np.arange(5))
Z += np.arange(5)
print(Z)

[0 1 2 3 4]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [159]:
# ??? count=-1?
# 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(), dtype=float, count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [164]:
# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [165]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.01794882 0.10648681 0.2129368  0.29759992 0.35406714 0.60784841
 0.60931315 0.65704355 0.72181107 0.87747195]


In [170]:
# 41. How to sum a small array faster than np.sum? (★★☆)
Z = np.arange(101) # 0 + 1 + 2 + ... + 100
# np.sum(Z)
np.add.reduce(Z)

5050

In [176]:
# ???
# 42. Consider two random array A and B, check if they are equal (★★☆)
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


In [181]:
# 43. Make an array immutable (read-only) (★★☆)
Z = np.zeros(10)
Z.flags.writeable = False
# Z[0] = 1 # error
Z.flags.writeable = True
Z[0] = 1 

In [186]:
# ???
# 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Z = np.random.random((10,2))
print(Z)
X,Y = Z[:,0], Z[:,1]
print(X)
print(Y)

R = np.sqrt(X**2 + Y **2)
T = np.arctan2(Y, X)
print('R', R)
print('T', T)

[[0.68908023 0.50282893]
 [0.79837012 0.6201818 ]
 [0.11207537 0.33944705]
 [0.38854862 0.79681857]
 [0.6086467  0.5373325 ]
 [0.50306159 0.75408222]
 [0.05743895 0.78716046]
 [0.18459368 0.43654312]
 [0.50699596 0.39718264]
 [0.73640355 0.80946408]]
[0.68908023 0.79837012 0.11207537 0.38854862 0.6086467  0.50306159
 0.05743895 0.18459368 0.50699596 0.73640355]
[0.50282893 0.6201818  0.33944705 0.79681857 0.5373325  0.75408222
 0.78716046 0.43654312 0.39718264 0.80946408]
R [0.85303487 1.01095021 0.35747054 0.8865043  0.81189717 0.90648274
 0.78925333 0.473967   0.64404887 1.09431361]
T [0.63038873 0.66043981 1.25189511 1.11709768 0.72324839 0.98248153
 1.49795562 1.17074538 0.66453916 0.83262485]


In [194]:
Z = np.random.random(6)
print(Z)
print(Z.argmax()) # return the index of max value
Z[Z.argmax()] = 0
print(Z)

[0.02530559 0.74310936 0.05404857 0.22124246 0.81786668 0.91208048]
5
[0.02530559 0.74310936 0.05404857 0.22124246 0.81786668 0.        ]


In [197]:
# ???  np.meshgrid?
# 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(8,9,5))
print(Z)

[[(0.  , 8.  ) (0.25, 8.  ) (0.5 , 8.  ) (0.75, 8.  ) (1.  , 8.  )]
 [(0.  , 8.25) (0.25, 8.25) (0.5 , 8.25) (0.75, 8.25) (1.  , 8.25)]
 [(0.  , 8.5 ) (0.25, 8.5 ) (0.5 , 8.5 ) (0.75, 8.5 ) (1.  , 8.5 )]
 [(0.  , 8.75) (0.25, 8.75) (0.5 , 8.75) (0.75, 8.75) (1.  , 8.75)]
 [(0.  , 9.  ) (0.25, 9.  ) (0.5 , 9.  ) (0.75, 9.  ) (1.  , 9.  )]]


In [199]:
# ??? np.subtract.outer(X, Y)
# ??? np.linalg.det(C)
# 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


In [201]:
# ??? np.finfo(dtype).eps
# 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
print()
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [208]:
# ???
# 49. How to print all the values of an array? (★★☆)
np.set_printoptions(threshold = np.nan)
Z = np.zeros((3, 3))
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [212]:
# 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
Z = np.arange(10)
V = np.random.uniform(0, 10)
print(Z)
print(V)
index = (np.abs(Z - V)).argmin()
print(Z[index])

[0 1 2 3 4 5 6 7 8 9]
9.55349991671081
9
